set(ITKBioCell_LOADED 1)
set(ITKBioCell_DEPENDS "ITKMesh")
set(ITKBioCell_LIBRARIES "ITKBioCell")
set(ITKBioCell_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Segmentation/BioCell/include")
set(ITKBioCell_LIBRARY_DIRS "")
