set(ITKBiasCorrection_LOADED 1)
set(ITKBiasCorrection_DEPENDS "ITKImageFilterBase;ITKImageGrid;ITKImageIntensity;ITKOptimizers;ITKPolynomials;ITKStatistics")
set(ITKBiasCorrection_LIBRARIES "ITKBiasCorrection")
set(ITKBiasCorrection_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Filtering/BiasCorrection/include")
set(ITKBiasCorrection_LIBRARY_DIRS "")
