set(ITKConnectedComponents_LOADED 1)
set(ITKConnectedComponents_DEPENDS "ITKImageGrid;ITKImageIntensity;ITKThresholding")
set(ITKConnectedComponents_LIBRARIES "ITKCommon;ITKStatistics;ITKSpatialObjects;ITKPath")
set(ITKConnectedComponents_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Segmentation/ConnectedComponents/include")
set(ITKConnectedComponents_LIBRARY_DIRS "")
