set(ITKColormap_LOADED 1)
set(ITKColormap_DEPENDS "ITKCommon")
set(ITKColormap_LIBRARIES "ITKCommon")
set(ITKColormap_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Filtering/Colormap/include")
set(ITKColormap_LIBRARY_DIRS "")
