set(ITKCurvatureFlow_LOADED 1)
set(ITKCurvatureFlow_DEPENDS "ITKFiniteDifference;ITKImageFilterBase")
set(ITKCurvatureFlow_LIBRARIES "ITKCommon")
set(ITKCurvatureFlow_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Filtering/CurvatureFlow/include")
set(ITKCurvatureFlow_LIBRARY_DIRS "")
