set(ITKDiffusionTensorImage_LOADED 1)
set(ITKDiffusionTensorImage_DEPENDS "ITKImageFeature;ITKSpatialObjects")
set(ITKDiffusionTensorImage_LIBRARIES "ITKCommon;ITKStatistics;ITKSpatialObjects;ITKPath")
set(ITKDiffusionTensorImage_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Filtering/DiffusionTensorImage/include")
set(ITKDiffusionTensorImage_LIBRARY_DIRS "")
