set(ITKDeconvolution_LOADED 1)
set(ITKDeconvolution_DEPENDS "ITKConvolution")
set(ITKDeconvolution_LIBRARIES "ITKCommon;ITKStatistics;ITKSpatialObjects;ITKPath")
set(ITKDeconvolution_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Filtering/Deconvolution/include")
set(ITKDeconvolution_LIBRARY_DIRS "")
