set(ITKDICOMParser_LOADED 1)
set(ITKDICOMParser_DEPENDS "")
set(ITKDICOMParser_LIBRARIES "ITKDICOMParser")
set(ITKDICOMParser_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/ThirdParty/DICOMParser/src/DICOMParser;/Users/antoinerosset/ITK/Modules/ThirdParty/DICOMParser/src/DICOMParser")
set(ITKDICOMParser_LIBRARY_DIRS "")
