set(ITKDeformableMesh_LOADED 1)
set(ITKDeformableMesh_DEPENDS "ITKAnisotropicSmoothing;ITKImageFeature;ITKImageIntensity;ITKMesh;ITKThresholding")
set(ITKDeformableMesh_LIBRARIES "ITKCommon;ITKStatistics;ITKSpatialObjects;ITKPath;ITKMesh")
set(ITKDeformableMesh_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Segmentation/DeformableMesh/include")
set(ITKDeformableMesh_LIBRARY_DIRS "")
