set(ITKEigen_LOADED 1)
set(ITKEigen_DEPENDS "ITKImageFilterBase")
set(ITKEigen_LIBRARIES "ITKCommon")
set(ITKEigen_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Numerics/Eigen/include")
set(ITKEigen_LIBRARY_DIRS "")
