set(ITKFastMarching_LOADED 1)
set(ITKFastMarching_DEPENDS "ITKCommon;ITKConnectedComponents;ITKQuadEdgeMesh")
set(ITKFastMarching_LIBRARIES "ITKCommon;ITKStatistics;ITKSpatialObjects;ITKPath;ITKQuadEdgeMesh")
set(ITKFastMarching_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Filtering/FastMarching/include")
set(ITKFastMarching_LIBRARY_DIRS "")
