set(ITKFEMRegistration_LOADED 1)
set(ITKFEMRegistration_DEPENDS "ITKFEM;ITKImageFeature;ITKImageStatistics;ITKPDEDeformableRegistration;ITKSpatialObjects")
set(ITKFEMRegistration_LIBRARIES "ITKFEM;ITKCommon;ITKStatistics;ITKSpatialObjects;ITKPath;ITKOptimizers")
set(ITKFEMRegistration_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Registration/FEM/include")
set(ITKFEMRegistration_LIBRARY_DIRS "")
