set(ITKHDF5_LOADED 1)
set(ITKHDF5_DEPENDS "ITKZLIB")
set(ITKHDF5_LIBRARIES "itkhdf5_cpp;itkhdf5")
set(ITKHDF5_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/ThirdParty/HDF5/src;/Users/antoinerosset/ITK/Modules/ThirdParty/HDF5/src")
set(ITKHDF5_LIBRARY_DIRS "")
