set(ITKIOMeta_LOADED 1)
set(ITKIOMeta_DEPENDS "ITKIOImageBase;ITKMetaIO")
set(ITKIOMeta_LIBRARIES "ITKIOMeta")
set(ITKIOMeta_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/IO/Meta/include")
set(ITKIOMeta_LIBRARY_DIRS "")
