set(ITKIOBioRad_LOADED 1)
set(ITKIOBioRad_DEPENDS "ITKIOImageBase")
set(ITKIOBioRad_LIBRARIES "ITKIOBioRad")
set(ITKIOBioRad_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/IO/BioRad/include")
set(ITKIOBioRad_LIBRARY_DIRS "")
