set(ITKImageCompare_LOADED 1)
set(ITKImageCompare_DEPENDS "ITKImageIntensity")
set(ITKImageCompare_LIBRARIES "ITKCommon;ITKStatistics;ITKSpatialObjects;ITKPath")
set(ITKImageCompare_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Filtering/ImageCompare/include")
set(ITKImageCompare_LIBRARY_DIRS "")
