set(ITKIOMesh_LOADED 1)
set(ITKIOMesh_DEPENDS "ITKCommon;ITKGIFTI;ITKIOImageBase;ITKMesh")
set(ITKIOMesh_LIBRARIES "ITKIOMesh")
set(ITKIOMesh_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/IO/Mesh/include")
set(ITKIOMesh_LIBRARY_DIRS "")
