set(ITKIOTransformInsightLegacy_LOADED 1)
set(ITKIOTransformInsightLegacy_DEPENDS "ITKIOTransformBase")
set(ITKIOTransformInsightLegacy_LIBRARIES "ITKIOTransformInsightLegacy")
set(ITKIOTransformInsightLegacy_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/IO/TransformInsightLegacy/include")
set(ITKIOTransformInsightLegacy_LIBRARY_DIRS "")
