set(ITKImageFeature_LOADED 1)
set(ITKImageFeature_DEPENDS "ITKImageGradient;ITKImageIntensity;ITKImageSource;ITKSmoothing;ITKSpatialObjects")
set(ITKImageFeature_LIBRARIES "ITKCommon;ITKStatistics;ITKSpatialObjects;ITKPath")
set(ITKImageFeature_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Filtering/ImageFeature/include")
set(ITKImageFeature_LIBRARY_DIRS "")
