set(ITKIOSpatialObjects_LOADED 1)
set(ITKIOSpatialObjects_DEPENDS "ITKIOImageBase;ITKIOXML;ITKSpatialObjects")
set(ITKIOSpatialObjects_LIBRARIES "ITKIOSpatialObjects")
set(ITKIOSpatialObjects_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/IO/SpatialObjects/include")
set(ITKIOSpatialObjects_LIBRARY_DIRS "")
