set(ITKIOSiemens_LOADED 1)
set(ITKIOSiemens_DEPENDS "ITKIOGE;ITKIOIPL")
set(ITKIOSiemens_LIBRARIES "ITKIOSiemens")
set(ITKIOSiemens_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/IO/Siemens/include")
set(ITKIOSiemens_LIBRARY_DIRS "")
