set(ITKImageFilterBase_LOADED 1)
set(ITKImageFilterBase_DEPENDS "ITKCommon")
set(ITKImageFilterBase_LIBRARIES "ITKCommon")
set(ITKImageFilterBase_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Filtering/ImageFilterBase/include")
set(ITKImageFilterBase_LIBRARY_DIRS "")
