set(ITKIOTransformMatlab_LOADED 1)
set(ITKIOTransformMatlab_DEPENDS "ITKIOTransformBase")
set(ITKIOTransformMatlab_LIBRARIES "ITKIOTransformMatlab")
set(ITKIOTransformMatlab_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/IO/TransformMatlab/include")
set(ITKIOTransformMatlab_LIBRARY_DIRS "")
