set(ITKIOTransformHDF5_LOADED 1)
set(ITKIOTransformHDF5_DEPENDS "ITKHDF5;ITKIOTransformBase")
set(ITKIOTransformHDF5_LIBRARIES "ITKIOTransformHDF5")
set(ITKIOTransformHDF5_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/IO/TransformHDF5/include")
set(ITKIOTransformHDF5_LIBRARY_DIRS "")
