set(ITKImageSource_LOADED 1)
set(ITKImageSource_DEPENDS "ITKImageFunction")
set(ITKImageSource_LIBRARIES "ITKCommon;ITKStatistics")
set(ITKImageSource_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Filtering/ImageSource/include")
set(ITKImageSource_LIBRARY_DIRS "")
