set(ITKIOStimulate_LOADED 1)
set(ITKIOStimulate_DEPENDS "ITKIOImageBase")
set(ITKIOStimulate_LIBRARIES "ITKIOStimulate")
set(ITKIOStimulate_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/IO/Stimulate/include")
set(ITKIOStimulate_LIBRARY_DIRS "")
