set(ITKIOTransformBase_LOADED 1)
set(ITKIOTransformBase_DEPENDS "ITKTransform")
set(ITKIOTransformBase_LIBRARIES "ITKIOTransformBase")
set(ITKIOTransformBase_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/IO/TransformBase/include")
set(ITKIOTransformBase_LIBRARY_DIRS "")
