set(ITKImageGradient_LOADED 1)
set(ITKImageGradient_DEPENDS "ITKImageIntensity;ITKSmoothing")
set(ITKImageGradient_LIBRARIES "ITKCommon;ITKStatistics;ITKSpatialObjects;ITKPath")
set(ITKImageGradient_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Filtering/ImageGradient/include")
set(ITKImageGradient_LIBRARY_DIRS "")
