set(ITKLabelVoting_LOADED 1)
set(ITKLabelVoting_DEPENDS "ITKThresholding")
set(ITKLabelVoting_LIBRARIES "ITKCommon;ITKStatistics;ITKSpatialObjects;ITKPath")
set(ITKLabelVoting_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Segmentation/LabelVoting/include")
set(ITKLabelVoting_LIBRARY_DIRS "")
