set(ITKLabelMap_LOADED 1)
set(ITKLabelMap_DEPENDS "ITKImageLabel;ITKMathematicalMorphology;ITKStatistics")
set(ITKLabelMap_LIBRARIES "ITKLabelMap")
set(ITKLabelMap_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Filtering/LabelMap/include")
set(ITKLabelMap_LIBRARY_DIRS "")
