set(ITKLevelSetsv4_LOADED 1)
set(ITKLevelSetsv4_DEPENDS "ITKCommon;ITKDistanceMap;ITKImageGradient;ITKLabelMap")
set(ITKLevelSetsv4_LIBRARIES "ITKCommon;ITKLabelMap;ITKStatistics;ITKSpatialObjects;ITKPath")
set(ITKLevelSetsv4_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Segmentation/LevelSetsv4/include")
set(ITKLevelSetsv4_LIBRARY_DIRS "")
