set(ITKMathematicalMorphology_LOADED 1)
set(ITKMathematicalMorphology_DEPENDS "ITKConnectedComponents;ITKImageGrid;ITKImageIntensity")
set(ITKMathematicalMorphology_LIBRARIES "ITKCommon;ITKStatistics;ITKSpatialObjects;ITKPath")
set(ITKMathematicalMorphology_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Filtering/MathematicalMorphology/include")
set(ITKMathematicalMorphology_LIBRARY_DIRS "")
