set(ITKNetlib_LOADED 1)
set(ITKNetlib_DEPENDS "ITKVNL")
set(ITKNetlib_LIBRARIES "itkNetlibSlatec")
set(ITKNetlib_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/ThirdParty/Netlib")
set(ITKNetlib_LIBRARY_DIRS "")
