set(ITKNeuralNetworks_LOADED 1)
set(ITKNeuralNetworks_DEPENDS "ITKStatistics")
set(ITKNeuralNetworks_LIBRARIES "ITKStatistics")
set(ITKNeuralNetworks_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Numerics/NeuralNetworks/include")
set(ITKNeuralNetworks_LIBRARY_DIRS "")
