set(ITKNrrdIO_LOADED 1)
set(ITKNrrdIO_DEPENDS "ITKZLIB")
set(ITKNrrdIO_LIBRARIES "ITKNrrdIO")
set(ITKNrrdIO_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/ThirdParty/NrrdIO/src/NrrdIO;/Users/antoinerosset/ITK/Modules/ThirdParty/NrrdIO/src/NrrdIO")
set(ITKNrrdIO_LIBRARY_DIRS "")
