set(ITKNIFTI_LOADED 1)
set(ITKNIFTI_DEPENDS "ITKZLIB")
set(ITKNIFTI_LIBRARIES "ITKznz;ITKniftiio")
set(ITKNIFTI_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/ThirdParty/NIFTI/src/nifti/niftilib;/Users/antoinerosset/ITK/Modules/ThirdParty/NIFTI/src/nifti/znzlib")
set(ITKNIFTI_LIBRARY_DIRS "")
