set(ITKNarrowBand_LOADED 1)
set(ITKNarrowBand_DEPENDS "ITKCurvatureFlow;ITKFiniteDifference;ITKImageIntensity")
set(ITKNarrowBand_LIBRARIES "ITKCommon;ITKStatistics;ITKSpatialObjects;ITKPath")
set(ITKNarrowBand_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Numerics/NarrowBand/include")
set(ITKNarrowBand_LIBRARY_DIRS "")
