set(ITKOptimizersv4_LOADED 1)
set(ITKOptimizersv4_DEPENDS "ITKCommon;ITKImageGrid;ITKOptimizers;ITKTransform")
set(ITKOptimizersv4_LIBRARIES "ITKOptimizersv4")
set(ITKOptimizersv4_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Numerics/Optimizersv4/include")
set(ITKOptimizersv4_LIBRARY_DIRS "")
