set(ITKOptimizers_LOADED 1)
set(ITKOptimizers_DEPENDS "ITKStatistics")
set(ITKOptimizers_LIBRARIES "ITKOptimizers")
set(ITKOptimizers_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Numerics/Optimizers/include")
set(ITKOptimizers_LIBRARY_DIRS "")
