set(ITKOpenJPEG_LOADED 1)
set(ITKOpenJPEG_DEPENDS "")
set(ITKOpenJPEG_LIBRARIES "itkopenjpeg")
set(ITKOpenJPEG_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/ThirdParty/OpenJPEG/src/openjpeg;/Users/antoinerosset/ITK/Modules/ThirdParty/OpenJPEG/src/openjpeg")
set(ITKOpenJPEG_LIBRARY_DIRS "")
