set(ITKPNG_LOADED 1)
set(ITKPNG_DEPENDS "ITKZLIB")
set(ITKPNG_LIBRARIES "itkpng")
set(ITKPNG_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/ThirdParty/PNG/src;/Users/antoinerosset/ITK/Modules/ThirdParty/PNG/src")
set(ITKPNG_LIBRARY_DIRS "")
