set(ITKPath_LOADED 1)
set(ITKPath_DEPENDS "ITKImageFilterBase;ITKImageFunction")
set(ITKPath_LIBRARIES "ITKPath")
set(ITKPath_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Filtering/Path/include")
set(ITKPath_LIBRARY_DIRS "")
