set(ITKStatistics_LOADED 1)
set(ITKStatistics_DEPENDS "ITKCommon;ITKNetlib")
set(ITKStatistics_LIBRARIES "ITKStatistics")
set(ITKStatistics_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Numerics/Statistics/include")
set(ITKStatistics_LIBRARY_DIRS "")
