set(ITKSignedDistanceFunction_LOADED 1)
set(ITKSignedDistanceFunction_DEPENDS "ITKImageFunction")
set(ITKSignedDistanceFunction_LIBRARIES "ITKCommon;ITKStatistics")
set(ITKSignedDistanceFunction_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Segmentation/SignedDistanceFunction/include")
set(ITKSignedDistanceFunction_LIBRARY_DIRS "")
