set(ITKTransform_LOADED 1)
set(ITKTransform_DEPENDS "ITKImageFilterBase;ITKStatistics")
set(ITKTransform_LIBRARIES "ITKCommon;ITKStatistics")
set(ITKTransform_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Core/Transform/include")
set(ITKTransform_LIBRARY_DIRS "")
