set(ITKTIFF_LOADED 1)
set(ITKTIFF_DEPENDS "ITKJPEG;ITKKWSys;ITKZLIB")
set(ITKTIFF_LIBRARIES "itktiff")
set(ITKTIFF_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/ThirdParty/TIFF/src;/Users/antoinerosset/ITK/Modules/ThirdParty/TIFF/src/itktiff;/Users/antoinerosset/ITK/Modules/ThirdParty/TIFF/src")
set(ITKTIFF_LIBRARY_DIRS "")
