set(ITKVideoCore_LOADED 1)
set(ITKVideoCore_DEPENDS "ITKCommon")
set(ITKVideoCore_LIBRARIES "ITKVideoCore")
set(ITKVideoCore_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Video/Core/include")
set(ITKVideoCore_LIBRARY_DIRS "")
