set(ITKVoronoi_LOADED 1)
set(ITKVoronoi_DEPENDS "ITKImageFilterBase;ITKMesh")
set(ITKVoronoi_LIBRARIES "ITKCommon;ITKMesh")
set(ITKVoronoi_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Segmentation/Voronoi/include")
set(ITKVoronoi_LIBRARY_DIRS "")
