set(ITKVNLInstantiation_LOADED 1)
set(ITKVNLInstantiation_DEPENDS "ITKVNL")
set(ITKVNLInstantiation_LIBRARIES "itkvnl_algo;itkvnl;itkv3p_netlib")
set(ITKVNLInstantiation_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/ThirdParty/VNLInstantiation/include")
set(ITKVNLInstantiation_LIBRARY_DIRS "")
