set(ITKVideoFiltering_LOADED 1)
set(ITKVideoFiltering_DEPENDS "ITKVideoCore")
set(ITKVideoFiltering_LIBRARIES "ITKVideoCore")
set(ITKVideoFiltering_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Video/Filtering/include")
set(ITKVideoFiltering_LIBRARY_DIRS "")
