set(ITKVNL_LOADED 1)
set(ITKVNL_DEPENDS "")
set(ITKVNL_LIBRARIES "itkvnl_algo;itkvnl;itkv3p_netlib")
set(ITKVNL_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/ThirdParty/VNL/src/vxl/v3p/netlib;/Users/antoinerosset/ITK/Modules/ThirdParty/VNL/src/vxl/vcl;/Users/antoinerosset/ITK/Modules/ThirdParty/VNL/src/vxl/core;/Users/antoinerosset/ITK/Modules/ThirdParty/VNL/src/vxl/v3p/netlib;/Users/antoinerosset/ITK/Modules/ThirdParty/VNL/src/vxl/vcl;/Users/antoinerosset/ITK/Modules/ThirdParty/VNL/src/vxl/core")
set(ITKVNL_LIBRARY_DIRS "")
