set(ITKWatersheds_LOADED 1)
set(ITKWatersheds_DEPENDS "ITKImageGradient;ITKImageIntensity;ITKSmoothing;ITKThresholding")
set(ITKWatersheds_LIBRARIES "ITKWatersheds")
set(ITKWatersheds_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/Segmentation/Watersheds/include")
set(ITKWatersheds_LIBRARY_DIRS "")
