set(ITKZLIB_LOADED 1)
set(ITKZLIB_DEPENDS "")
set(ITKZLIB_LIBRARIES "itkzlib")
set(ITKZLIB_INCLUDE_DIRS "/Users/antoinerosset/ITK/Modules/ThirdParty/ZLIB/src;/Users/antoinerosset/ITK/Modules/ThirdParty/ZLIB/src")
set(ITKZLIB_LIBRARY_DIRS "")
